export enum ReduxActionTypes {
  CHANGE_THEME = "CHANGE_THEME",
  THEME_WAS_CHANGED = "THEME_WAS_CHANGED",
  TOGGLE_NIGHTMODE = "TOGGLE_NIGHTMODE",
  OPEN_CONTEXT_MENU = "OPEN_CONTEXT_MENU",
  CLOSE_CONTEXT_MENU = "CLOSE_CONTEXT_MENU",
  CHANGE_BRIGHTNESS = "CHANGE_BRIGHTNESS",
  SORT_DESKTOP = "SORT_DESKTOP",
  CHANGE_ICON_SIZE = "CHANGE_ICON_SIZE",
  OPEN_WINDOW = "OPEN_WINDOW",
  CLOSE_WINDOW = "CLOSE_WINDOW",
  CLEAR_CLOSED_WINDOWS = "CLEAR_CLOSED_WINDOWS",
}
