import process from "node:process";
import { writeFile } from "node:fs/promises";
import type { Profile } from "../src/types";

if (!process.env.GITHUB_TOKEN) {
  throw new Error("No GITHUB_TOKEN found");
}

const NAME = "luxass";

const QUERY = `query GetProfile($name: String!) {
  user(login: $name) {
    repositories(
      first: 100
      orderBy: { direction: ASC, field: PUSHED_AT }
      privacy: PUBLIC
    ) {
      totalCount
      nodes {
        name
        owner {
          login
        }
        description
        pushedAt
        url
        languages(first: 1, orderBy: { field: SIZE, direction: DESC }) {
          nodes {
            color
            name
          }
        }
        object(expression: "HEAD:.github") {
          ... on Tree {
            entries {
              name
              type
            }
          }
        }
      }
    }
  }
}`;

const BANNER = "// this file is generated by scripts/fetch-projects.ts";

async function run() {
  const { data: profile } = (await fetch("https://api.github.com/graphql", {
    method: "POST",
    headers: {
      "Authorization": `bearer ${process.env.GITHUB_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      query: QUERY,
      variables: { name: NAME },
    }),
  }).then((res) => res.json())) as { data: Profile };

  if (!profile) {
    throw new Error("No profile found");
  }

  const repos = profile.user.repositories.nodes
    .filter((repo) => {
      if (repo.object?.entries?.length) {
        return repo.object.entries.some((entry) => entry.name === ".luxass");
      }

      return false;
    })
    .sort(
      (a, b) => new Date(b.pushedAt).getTime() - new Date(a.pushedAt).getTime(),
    );

  if (!repos) {
    throw new Error("No repos found");
  }

  await writeFile("./src/projects.ts", `${BANNER}\n\nexport const projects = ${JSON.stringify(repos.map((repo) => ({
    name: repo.name,
    owner: repo.owner.login,
    description: (
      repo.description || "No description was provided."
    ).replaceAll(/:\w+:/gm, ""),
    url: repo.url,
    pushedAt: repo.pushedAt,
    language: repo.languages.nodes[0],
  })))};\n`);
}

run().catch((err) => {
  console.error(err);
  process.exit(1);
});
