// this file is generated by scripts/fetch-projects.ts

export const projects = [
  {
    "name": "jsonc-parse",
    "owner": "luxass",
    "description": "A lightweight JSON with Comments parser.",
    "url": "https://github.com/luxass/jsonc-parse",
    "pushedAt": "2023-09-29T17:49:02Z",
    "language": {
      "color": "#3178c6",
      "name": "TypeScript"
    }
  },
  {
    "name": "cdn-resolve",
    "owner": "luxass",
    "description": "Resolves packages to their relative CDN URLS",
    "url": "https://github.com/luxass/cdn-resolve",
    "pushedAt": "2023-09-29T17:19:16Z",
    "language": {
      "color": "#3178c6",
      "name": "TypeScript"
    }
  },
  {
    "name": "esbuild-cdn-imports",
    "owner": "luxass",
    "description": "This plugin intercepts imports and resolves them to a CDN URL.",
    "url": "https://github.com/luxass/esbuild-cdn-imports",
    "pushedAt": "2023-09-29T17:07:01Z",
    "language": {
      "color": "#3178c6",
      "name": "TypeScript"
    }
  },
  {
    "name": "neoman",
    "owner": "luxass",
    "description": "No description was provided.",
    "url": "https://github.com/luxass/neoman",
    "pushedAt": "2023-09-29T16:53:55Z",
    "language": {
      "color": "#3178c6",
      "name": "TypeScript"
    }
  },
  {
    "name": "luxass.dev",
    "owner": "luxass",
    "description": "My personal website",
    "url": "https://github.com/luxass/luxass.dev",
    "pushedAt": "2023-09-29T16:34:54Z",
    "language": {
      "color": "#ff5a03",
      "name": "Astro"
    }
  },
  {
    "name": "tsup-problem-matchers",
    "owner": "luxass",
    "description": "Problem matchers for tsup tasks in VSCode",
    "url": "https://github.com/luxass/tsup-problem-matchers",
    "pushedAt": "2023-09-29T16:24:07Z",
    "language": {
      "color": "#f1e05a",
      "name": "JavaScript"
    }
  },
  {
    "name": "tsconf-utils",
    "owner": "luxass",
    "description": "Utilities for working with tsconfig.json files",
    "url": "https://github.com/luxass/tsconf-utils",
    "pushedAt": "2023-09-29T16:18:14Z",
    "language": {
      "color": "#3178c6",
      "name": "TypeScript"
    }
  },
  {
    "name": "load-config",
    "owner": "luxass",
    "description": "No description was provided.",
    "url": "https://github.com/luxass/load-config",
    "pushedAt": "2023-09-29T15:10:38Z",
    "language": {
      "color": "#3178c6",
      "name": "TypeScript"
    }
  },
  {
    "name": "elysius",
    "owner": "luxass",
    "description": "Find a file or directory by traversing",
    "url": "https://github.com/luxass/elysius",
    "pushedAt": "2023-09-04T16:18:44Z",
    "language": {
      "color": "#3178c6",
      "name": "TypeScript"
    }
  },
  {
    "name": "prettier-config",
    "owner": "luxass",
    "description": "No description was provided.",
    "url": "https://github.com/luxass/prettier-config",
    "pushedAt": "2023-06-20T15:03:41Z",
    "language": {
      "color": "#f1e05a",
      "name": "JavaScript"
    }
  },
  {
    "name": "typeschema",
    "owner": "luxass",
    "description": "Generate JSON Schemas, Zod Schemas from TypeScript types.",
    "url": "https://github.com/luxass/typeschema",
    "pushedAt": "2023-06-20T14:53:59Z",
    "language": {
      "color": "#3178c6",
      "name": "TypeScript"
    }
  },
  {
    "name": "action-trending",
    "owner": "luxass",
    "description": "No description was provided.",
    "url": "https://github.com/luxass/action-trending",
    "pushedAt": "2023-06-01T06:03:06Z",
    "language": {
      "color": "#3178c6",
      "name": "TypeScript"
    }
  }
];
