// THIS FILE IS AUTOGENERATED BY ./scripts/update-site.ts. DO NOT EDIT THIS FILE DIRECTLY.

export type Project = typeof projects[number];

export const projects = [
  {
    name: ".vscode",
    nameWithOwner: "luxass/.vscode",
    description: "My VSCode config",
    pushedAt: "2023-09-25T05:18:20Z",
    url: "https://github.com/luxass/.vscode",
    defaultBranch: "main",
    projectrc: {
      readme: false,
      npm: false,
      ignore: false,
    },
    language: {
      name: "Unknown",
      color: "#333",
    },
    isContributor: false,
  },
  {
    name: "eslint-config",
    nameWithOwner: "luxass/eslint-config",
    description: null,
    pushedAt: "2023-09-24T13:05:44Z",
    url: "https://github.com/luxass/eslint-config",
    defaultBranch: "main",
    projectrc: {
      readme: true,
      npm: true,
      ignore: false,
    },
    language: {
      name: "TypeScript",
      color: "#3178c6",
    },
    isContributor: false,
  },
  {
    name: "github-schema",
    nameWithOwner: "luxass/github-schema",
    description: "GitHub's GraphQL schema",
    pushedAt: "2023-09-23T05:51:52Z",
    url: "https://github.com/luxass/github-schema",
    defaultBranch: "main",
    projectrc: {
      readme: true,
      npm: true,
      ignore: false,
    },
    language: {
      name: "TypeScript",
      color: "#3178c6",
    },
    isContributor: false,
  },
  {
    name: "github-emojis",
    nameWithOwner: "luxass/github-emojis",
    description: "A list of all available emojis on GitHub",
    pushedAt: "2023-09-23T13:21:13Z",
    url: "https://github.com/luxass/github-emojis",
    defaultBranch: "main",
    projectrc: {
      readme: true,
      npm: true,
      ignore: false,
    },
    language: {
      name: "TypeScript",
      color: "#3178c6",
    },
    isContributor: false,
  },
  {
    name: "eslint-config-legacy",
    nameWithOwner: "luxass/eslint-config-legacy",
    description: "My old shareable ESLint config",
    pushedAt: "2023-09-24T06:23:22Z",
    url: "https://github.com/luxass/eslint-config-legacy",
    defaultBranch: "main",
    projectrc: {
      readme: false,
      npm: true,
      ignore: false,
    },
    language: {
      name: "JavaScript",
      color: "#f1e05a",
    },
    isContributor: false,
  },
  {
    name: "schemastore",
    nameWithOwner: "SchemaStore/schemastore",
    description: "A collection of JSON schema files including full API",
    pushedAt: "2023-09-27T10:28:34Z",
    url: "https://github.com/SchemaStore/schemastore",
    defaultBranch: "master",
    language: {
      name: "JavaScript",
      color: "#f1e05a",
    },
    isContributor: true,
  },
];
